name: shared_widgets
description: عناصر واجهة مستخدم مشتركة بين التطبيقات.
version: 1.0.0

publish_to: 'none'

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_models:
    path: ../shared_models
  shared_services:
    path: ../shared_services

  path_provider: ^2.1.1
  stack_trace: ^1.11.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
